version: "2"

services:
  vote:
    image: ${REPO_PREFIX}/vote:${BUILD_BUILDNUMBER}
    command: python app.py
    ports:
      - "5000:80"
    environment:
      - "constraint:node==ddc0-ucpnode"
    networks: 
      - voteapp
      
  redis:
    image: redis:alpine
    ports: ["6379"]
    environment:
      - "constraint:node==ddc0-ucpnode"
    networks: 
      - voteapp


  worker:
    image: ${REPO_PREFIX}/worker:${BUILD_BUILDNUMBER}
    environment:
      - "constraint:node==ddc0-ucpnode"
    networks: 
      - voteapp

  db:
    image: postgres:9.4
    environment:
      - "constraint:node==ddc0-ucpnode"
    networks: 
      - voteapp

  result:
    image: ${REPO_PREFIX}/result:${BUILD_BUILDNUMBER}
    command: nodemon --debug server.js
    ports:
      - "5001:80"
      - "5858:5858"
    environment:
      - "constraint:node==ddc0-ucpnode"
    networks: 
      - voteapp

networks: 
      voteapp: